/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PP_Factory_Method_Pessoa;

public class App {
   
    public static void main(String[] args) {
        FactoryPessoa factory = new FactoryPessoa();
        
        String nome = "Jose";
        String sexo = "m";
        
        factory.getPessoa(nome, sexo);
        
        nome = "Maria";
        sexo = "f";
        
        factory.getPessoa(nome, sexo);
        
    }
}
